'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace Controls
    Partial Public Class DateRange2
        Protected WithEvents rblDateRange As System.Web.UI.WebControls.RadioButtonList
        Protected WithEvents dtbStartDate As PeterBlum.PetersDatePackage.DateTextBox
        Protected WithEvents hidStartDate As System.Web.UI.HtmlControls.HtmlInputHidden
        Protected WithEvents dtbEndDate As PeterBlum.PetersDatePackage.DateTextBox
        Protected WithEvents hidEndDate As System.Web.UI.HtmlControls.HtmlInputHidden
        Protected WithEvents pnlDaySelection As System.Web.UI.WebControls.Panel
        Protected WithEvents rblDaySelection As System.Web.UI.WebControls.RadioButtonList
        Protected WithEvents pnlMonthSelection As System.Web.UI.WebControls.Panel
        Protected WithEvents rblMonthSelection As System.Web.UI.WebControls.RadioButtonList
        Protected WithEvents pnlYearSelection As System.Web.UI.WebControls.Panel
        Protected WithEvents rblYearSelection As System.Web.UI.WebControls.RadioButtonList
        Protected WithEvents pnlRangeSelection As System.Web.UI.WebControls.Panel
        Protected WithEvents rblRangeSelection As System.Web.UI.WebControls.RadioButtonList
        Protected WithEvents dmvStartDate As PeterBlum.PetersDatePackage.DateTextBoxMinMaxValidator
        Protected WithEvents dtvStartDate As PeterBlum.PetersDatePackage.DateTextBoxValidator
        Protected WithEvents dmvEndDate As PeterBlum.PetersDatePackage.DateTextBoxMinMaxValidator
        Protected WithEvents dtvEndDate As PeterBlum.PetersDatePackage.DateTextBoxValidator
    End Class
End Namespace
