'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Controls

    Partial Public Class Footer2

        '''<summary>
        '''litCopyright control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litCopyright As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litHelpLinks control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litHelpLinks As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litGoogleAnalytics control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litGoogleAnalytics As Global.System.Web.UI.WebControls.Literal
    End Class
End Namespace
