'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Controls

    Partial Public Class PromotionHeader

        '''<summary>
        '''divPromoLogo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divPromoLogo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblReportTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReportTitle As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblReportDesc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReportDesc As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTimeNotification control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTimeNotification As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblLastRefreshTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLastRefreshTime As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblNextRefreshTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNextRefreshTime As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''pnlWorldExplorer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlWorldExplorer As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''rblSecurityType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblSecurityType As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''tdTitlePremium control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdTitlePremium As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''spnTitlePremium control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnTitlePremium As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''tdTitleDeluxe control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdTitleDeluxe As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''spnTitleDeluxe control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnTitleDeluxe As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''tdTitleLuxuryRiver control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdTitleLuxuryRiver As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''spnTitleLuxuryRiver control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnTitleLuxuryRiver As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''tdTitleProspects control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdTitleProspects As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''spnTitleProspects control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnTitleProspects As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''tdTitleOther control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdTitleOther As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''spnTitleOther control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnTitleOther As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''rptWorldExplorer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptWorldExplorer As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''pnlSeasToday control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlSeasToday As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''spnLabelSTC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnLabelSTC As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''rblSTCSecurityType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblSTCSecurityType As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''tdTitleSTCIdealProspects control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdTitleSTCIdealProspects As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''spnTitleSTCIdealProspects control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnTitleSTCIdealProspects As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''tdTitleSTCProspects control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdTitleSTCProspects As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''spnTitleSTCProspects control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnTitleSTCProspects As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''tdTitleSTCOther control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdTitleSTCOther As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''spnTitleSTCOther control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnTitleSTCOther As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''rptSeasToday control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptSeasToday As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''pnlEEC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlEEC As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''spnLabelEEC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnLabelEEC As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''rblEECSecurityType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblEECSecurityType As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''tdTitleEECIdealCustomers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdTitleEECIdealCustomers As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''spnTitleEECIdealCustomers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnTitleEECIdealCustomers As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''tdTitleEECPastCustomers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdTitleEECPastCustomers As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''spnTitleEECPastCustomers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnTitleEECPastCustomers As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''tdTitleEECIdealProspects control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdTitleEECIdealProspects As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''spnTitleEECIdealProspects control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnTitleEECIdealProspects As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''tdTitleEECOther control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdTitleEECOther As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''spnTitleEECOther control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnTitleEECOther As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''EECRepeater control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EECRepeater As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''pnlSSC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlSSC As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''spnLabelSSC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnLabelSSC As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''rblSSCSecurityType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblSSCSecurityType As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''tdTitleSSCIdealCustomers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdTitleSSCIdealCustomers As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''spnTitleSSCIdealCustomers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnTitleSSCIdealCustomers As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''tdTitleSSCPastCustomers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdTitleSSCPastCustomers As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''spnTitleSSCPastCustomers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnTitleSSCPastCustomers As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''tdTitleSSCProspects control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdTitleSSCProspects As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''spnTitleSSCProspects control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnTitleSSCProspects As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''tdTitleSSCOther control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdTitleSSCOther As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''spnTitleSSCOther control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnTitleSSCOther As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''SSCRepeater control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SSCRepeater As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''pnlLRC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlLRC As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''spnLabelLRC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnLabelLRC As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''rblLRCSecurityType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblLRCSecurityType As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''tdTitleLRCList1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdTitleLRCList1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''spnTitleLRClist1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnTitleLRClist1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''tdTitleLRCList2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdTitleLRCList2 As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''spnTitleLRClist2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnTitleLRClist2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''tdTitleLRCList3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdTitleLRCList3 As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''spnTitleLRClist3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnTitleLRClist3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''tdTitleLRCList4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdTitleLRCList4 As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''spnTitleLRClist4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnTitleLRClist4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''LRCRepeater control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LRCRepeater As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''pnlOneDaySale control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlOneDaySale As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''spnLabelOSC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnLabelOSC As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''rblOSCSecurityType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblOSCSecurityType As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''tdListOSC1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdListOSC1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''spnTitleOSClist1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnTitleOSClist1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''tdListOSC2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdListOSC2 As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''spnTitleOSClist2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnTitleOSClist2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''tdListOSC3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdListOSC3 As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''spnTitleOSClist3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnTitleOSClist3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''tdListOSC4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdListOSC4 As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''spnTitleOSClist4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnTitleOSClist4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''OSCRepeater control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents OSCRepeater As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''pnlEAC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlEAC As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''spnLabelEAC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnLabelEAC As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''rblEACSecurityType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblEACSecurityType As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''tdTitleEACEuropeAlaskaCustomers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdTitleEACEuropeAlaskaCustomers As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''spnTitleEACEuropeAlaskaCustomers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnTitleEACEuropeAlaskaCustomers As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''tdTitleEACEuropeCustomers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdTitleEACEuropeCustomers As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''spnTitleEACEuropeCustomers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnTitleEACEuropeCustomers As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''tdTitleEACAlaskaCustomers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdTitleEACAlaskaCustomers As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''spnTitleEACAlaskaCustomers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnTitleEACAlaskaCustomers As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''tdTitleEACProspects control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdTitleEACProspects As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''spnTitleEACProspects control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnTitleEACProspects As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''tdTitleEACOther control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdTitleEACOther As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''spnTitleEACOther control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnTitleEACOther As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''EACRepeater control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EACRepeater As Global.System.Web.UI.WebControls.Repeater
    End Class
End Namespace
