Open SQL Management Studio on the Data Warehouse Server and run the following command substituting the User Display name you want to find the UserDimKey for.

    /****** Script for SelectTopNRows command from SSMS  ******/
    SELECT TOP 1000 [AssetStatus]
          ,[AssetStatus_ConfigItemAssetStatusId]
          ,[BaseManagedEntityId]
          ,[BusinessPhone]
          ,[BusinessPhone2]
          ,[City]
          ,[Company]
          ,[Country]
          ,[Department]
          ,[DisplayName]
          ,[DistinguishedName]
          ,[Domain]
          ,[EmployeeId]
          ,[EntityDimKey]
          ,[Fax]
          ,[FirstName]
          ,[FQDN]
          ,[HomePhone]
          ,[HomePhone2]
          ,[Initials]
          ,[InsertedBatchId]
          ,[IsDeleted]
          ,[LastName]
          ,[Mobile]
          ,[Notes]
          ,[ObjectStatus]
          ,[ObjectStatus_ConfigItemObjectStatusId]
          ,[Office]
          ,[Pager]
          ,[SID]
          ,[SourceId]
          ,[State]
          ,[StreetAddress]
          ,[Title]
          ,[UpdatedBatchId]
          ,[UPN]
          ,[UserDimKey]
          ,[UserName]
          ,[Zip]
      FROM [DWDataMartR2].[dbo].[UserDimvw] where [DisplayName] = ‘DisplayNameofUserInActiveDirectory
